version: '3.9'
services:
  web:
    image: malarg/device_app:v1
    ports:
        - "80:5000"
    environment:
      MONGO_ATLAS_URL: mongodb+srv://device_user:device_password@cluster0.zjihjqh.mongodb.net/?retryWrites=true&w=majority
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
        - "2181:2181"
    environment:
      KAFKA_HEAP_OPTS: '-Xms4g -Xmx4g'
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    depends_on:
      - zookeeper
    restart: on-failure
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_HEAP_OPTS: '-Xms2g -Xmx2g'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: 0.0.0.0
  socket:
    image: malarg/socket:v1
    ports:
        - "12345:12345"
    environment:
      SOCKET_SERVER_PORT: 12345
  producer:
    image: malarg/producer:v1
    depends_on:
      - socket
      - broker
    environment:
      SOCKET_SERVER_HOST: socket
      SOCKET_SERVER_PORT: 12345
      BOOTSTRAP_SERVER: 'broker:29092'
      TOPIC_NAME: device_data
  consumer:
    image: malarg/consumer:v1
    depends_on:
      - broker
    environment:
      BOOTSTRAP_SERVER: 'broker:29092'
      TOPIC_NAME: device_data
      MONGO_ATLAS_URL: mongodb+srv://device_user:device_password@cluster0.zjihjqh.mongodb.net/?retryWrites=true&w=majority